a = input('Digite algo: ')
print('tipo primitivo: {}'.format(type(a)))
print('tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('é alfabético? ', a.isalpha())
print('é alfanumérico', a.isalnum())
print('está em maiusculas? ', a.isupper())
print('está em minusculas? ', a.islower())
print('está capitalizada? ', a.istitle())
